baseURL = "https://protolabz.github.io/my-blog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "pulp"
snipcart_test_api_key = "YzlkMGYxZTgtM2MzZi00M2Q2LWEwOTEtODcyMDY3YjFhNWM3NjM2OTk1NDk0NjI3NzU5NzM0"
